bookmarks/bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

bookmarks/images/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)

    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

bookmarks/images/forms.py
import requests
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given url
        response = requests.get(image_url)
        image.image.save(image_name, ContentFile(response.content), save=False)
        if commit:
            image.save()
        return image

bookmarks/images/views.py
import redis
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from actions.utils import create_action
from .forms import ImageCreateForm
from .models import Image

r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB, )


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
        print(request.GET)
        return render(request,
                      'images/image/create.html',
                      {'section': 'images',
                       'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr(f'image:{image.id}:views')
    r.zincrby('image_ranking', 1, image.id)
    return render(request,
                  'images/image/detail.html',
                  {'section': 'image',
                   'image': image,
                   'total_views': total_views})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    template_name = 'images/image/list_images.html' if images_only else 'images/image/list.html'
    return render(request, template_name,
                  {'section': 'images',
                   'images': images})


@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})

bookmarks/images/templates/images/image/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Bookmark an image{% endblock title %}

{% block content %}

	<div class="row">
		<div class="col">
			<h1 class="text-center">Bookmark an image</h1>
			<hr>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-lg-4 col-md-6 col-sm-12">
			<img src="{{ request.GET.url }}" class="img-fluid mb-3">
		</div>
		<div class="col-lg-4 col-md-6 col-sm-12">
			<form method="post">
				{% csrf_token %}
				{% bootstrap_form form show_label=False %}
				{% bootstrap_button button_class="btn-primary w-100" button_type="submit" content="Bookmark it!" %}
			</form>
		</div>
	</div>

{% endblock content %}

bookmarks/images/templates/images/image/detail.html
{% extends 'base.html' %}
{% block title %}{{ image.title }}{% endblock title %}

{% block content %}

	<div class="row">
		<div class="col">
			<h1 class="text-center">{{ image.title }}</h1>
			<hr class="mb-4">
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-lg-4 col-md-6 col-sm-12 mb-3">
			{% load thumbnail %}
			<a href="{{ image.image.url }}">
				<img class="img-fluid" src="{% thumbnail image.image 300x0 %}">
			</a>
		</div>
		{% with total_likes=image.users_like.count users_like=image.users_like.all %}
			<div class="col-lg-4 col-md-6 col-sm-12">
				{# Like-Unlike #}
				<div class="mb-2 d-flex justify-content-between">
					<span class="count border border-success rounded-pill px-3 py-2">
						<span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
					</span>
					<span class="count border border-success rounded-pill px-3 py-2">
						{{ total_views }} view{{ total_views|pluralize }}
					</span>
					<a class="like btn btn-success text-uppercase fw-bold"
						 href="#"
						 data-id="{{ image.id }}"
						 data-action="{% if request.user in users_like %}un{% endif %}like">
						{% if request.user not in users_like %}
							Like
						{% else %}
							Unlike
						{% endif %}
					</a>
				</div>
				{{ image.description|linebreaks }}
				<div class="d-flex">
					{% for user in users_like %}
						<div class="d-flex">
							{% if user.profile.photo %}
								<img style="width: 50px; height: 50px" class="img-thumbnail rounded-circle" src="{{ user.profile.photo.url }}">
							{% endif %}
						</div>
					{% empty %}
						Nobody likes this image yet
					{% endfor %}
				</div>
			</div>
		{% endwith %}
	</div>

{% endblock content %}

{% block domready %}

	const url = '{% url "images:like" %}';
	let options = {
		method: 'POST',
		headers: {'X-CSRFToken': csrftoken},
		mode: 'same-origin'
	}
	document.querySelector('a.like').addEventListener('click', function(e) {
		e.preventDefault();
		let likeButton = this;
	
		// add request body
		let formData = new FormData()
		formData.append('id', likeButton.dataset.id)
		formData.append('action', likeButton.dataset.action)
		options['body'] = formData;
		// send Http request
		fetch(url, options)
		.then(response => response.json())
		.then(data => {
			if (data['status'] === 'ok') {
				let previousAction = likeButton.dataset.action;

				//toogle button text and action
				let action = previousAction === 'like' ? 'unlike' : 'like';
				likeButton.dataset.action = action;
				likeButton.innerHTML = action;

				//update likes count
				let likeCount = document.querySelector('span.count .total');
				let totalLikes = parseInt(likeCount.innerHTML);
				likeCount.innerHTML = previousAction === 'like'? totalLikes + 1 : totalLikes - 1;
				
			}
		})
	});
{% endblock domready %}

bookmarks/images/templates/images/image/list.html
{% extends 'base.html' %}
{% block title %}Images bookmarked{% endblock title %}

{% block content %}

	<div class="row">
		<div class="col">
			<h1 class="text-center">Images bookmarked</h1>
			<hr>
		</div>
	</div>
	<div class="row">
		<div class="col d-flex justify-content-center flex-wrap" id="image-list">
			{% include "images\image\list_images.html" %}
		</div>
	</div>
{% endblock content %}

{% block domready %}

	let page = 1;
	let emptyPage = false;
	let blockRequest = false;

	window.addEventListener('scroll', function(e) {
		let margin = document.body.clientHeight - window.innerHeight - 200;
		if (window.pageYOffset > margin && !emptyPage && !blockRequest) {
			blockRequest = true;
			page += 1;

			fetch('?images_only=1&page=' + page)
			.then(response => response.text())
			.then(html => {
				if (html === '') {
					emptyPage = true;
				}
				else {
					let imageList = document.getElementById('image-list');
					imageList.insertAdjacentHTML('beforeEnd', html);
					blockRequest = false;
				}
			})
		}
	})
	// Lauch scroll event
	const scrollEvent = new Event('scroll');
	window.dispatchEvent(scrollEvent);

{% endblock domready %}

bookmarks/images/templates/images/image/list_images.html
{% load thumbnail %}
{% for image in images %}
	<div class="card" style="width: 18rem;">
		{% thumbnail image.image 300x300 crop="smart" as im%}
		<a href="{{ image.get_absolute_url }}">
			<img class="card-img" src="{{ im.url }}">
		</a>
		<div class="card-body">
			<a class="card-text" href="{{ image.get_absolute_url }}">{{ image.title }}</a>
		</div>
	</div>
{% endfor %}

bookmarks/images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% block title %}Images ranking{% endblock title %}

{% block content %}

	<div class="row">
		<div class="col">
			<h1 class="text-center">Images ranking</h1>
			<hr>
			<ol>
				{% for image in most_viewed %}
					<li>
						<a href="{{ image.get_absolute_url }}">
							{{ image.title }}
						</a>
					</li>
				{% endfor %}
			</ol>
		</div>
	</div>

{% endblock content %}